goclimate/goclimate

- app/controllers/application_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/welcome_controller.rb
- app/models/card_charge.rb
- app/models/currency.rb
- app/models/gift_card.rb
- app/models/impact_statistics.rb
- app/models/lifestyle_choice.rb
> Move currency rates to Currency

- app/assets/main/controllers/lifestyle_footprint_controller.js
- app/assets/stylesheets/components/button.scss
- app/views/lifestyle_footprints/new.html.erb
- app/views/welcome/about.html.erb
- tailwind.config.js
> Calculator UI

- db/migrate/20200413073358_add_country_to_lifestyle_footprints.rb
- db/schema.rb
> Migrate LifestyleFootprints to include country

- app/models/lifestyle_footprint_average.rb
- spec/models/lifestyle_footprint_average_spec.rb
@emmabckstrm We can either cherry-pick this into your current branch or just merge before.
> Add lifestyle footprint averages for use in comparisons

- app/assets/main/components/button.scss
- app/assets/main/components/collapse.scss
- app/assets/main/components/dropdown.scss
- app/assets/main/components/input.scss
- app/assets/main/components/link.scss
- app/assets/main/components/section_gutter.scss
- app/assets/main/components/section_padding.scss
- app/assets/main/components/select.scss
- app/assets/main/index.scss
- app/views/devise/registrations/new_alternative.html.erb
- app/views/lifestyle_footprints/new.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_prefooter.html.erb
- app/views/welcome/about.html.erb
- tailwind.config.js
Verify that these pages look OK (in line with old/current design) with new config:
> New tailwind config

- app/controllers/application_controller.rb
- app/views/welcome/index.html.erb
- config/experiments.yml
- spec/features/registrations_spec.rb
Of the three current variants (old calculator + old sign up, new calculator + old sign up, new calculator + new sign up), this one has performed worst by far.
> Stop testing new calculator with old sign up

- app/helpers/application_helper.rb
- app/views/application/_third_party_javascripts.html.erb
- app/views/layouts/application.html.erb
Also moves all third party JS to one place to make it easier to get an overview.
> Honor Do Not Track headers set by clients

- app/assets/main/controllers/lifestyle_footprint_chart_controller.js
when there is a big difference between the bars
> make sure the number of the sign up chart is not cut off

- app/controllers/users/registrations_controller.rb
- app/views/devise/registrations/new_alternative.html.erb
- app/views/devise/registrations/new_alternative_new.html.erb
- app/views/shared/_header_old_tailwind.html.erb
- config/locales/en.yml
- config/locales/sv.yml
- db/seeds.rb
- spec/features/registrations_spec.rb
> Signup fixes

- app/views/home/show_new.html.erb
We're pretty clear ourselves on the importance of creating a feeling that we're doing this together. This was confirmed again in user testing I did yesterday where the person said "oh, this is very important" to this section that we actually put way at the bottom of the home page.
> Move community to top of home page to improve relatability

- app/views/home/show_new.html.erb
- app/views/projects/index_new.html.erb
- Uses our tagline as the title for our home page
- Fixes projects page to use actual title
> Tweak page titles

- app/views/about/faq/show_new.html.erb
Review app: https://goclimateneutral-stagin-pr-336.herokuapp.com/
> New design FAQ page

- app/assets/main/components/divider.scss
- app/assets/main/index.scss
- app/views/about/transparency/show_new.html.erb
Review link: https://goclimateneutral-stagin-pr-337.herokuapp.com/transparency?enable_experiments=new_design
> Add new design for 100% transparency page

- app/controllers/about/privacy_policy_controller.rb
- app/views/about/privacy_policy/show_new.html.erb
> New design privacy policy

- app/views/about/contact/show_new.html.erb
> Add new design for contact us page

- app/controllers/gift_cards_controller.rb
- app/views/gift_cards/index.html.erb
- app/views/gift_cards/index_new.html.erb
- app/views/gift_cards/new_new.html.erb
- app/views/gift_cards/thank_you_new.html.erb
- config/locales/views/gift_cards.en.yml
- config/locales/views/gift_cards.sv.yml
- spec/features/gift_cards_spec.rb
> New design gift cards

- app/assets/main/components/README.md
- app/assets/main/components/dropdown.scss
- app/assets/main/components/select.scss
- app/assets/main/controllers/airport_field_controller.js
- app/assets/main/controllers/lifestyle_calculator_controller.js
- app/assets/util/swap_classes.js
- app/controllers/flight_offsets_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/registrations/new_new.html.erb
- app/views/flight_footprints/new.html.erb
- app/views/flight_footprints/new_new.html.erb
- app/views/flight_offsets/new_new.html.erb
- app/views/flight_offsets/thank_you_new.html.erb
- app/views/home/show_new.html.erb
- config/locales/views/flight_offsets.en.yml
- config/locales/views/flight_offsets.sv.yml
In order to make the design good enough there were some smaller things I fixed in other places as well. See commits.
- Make airport field controller be less strict in what markup it allows
- Simplify markup for select CSS component
- Z-index correction on dropdown component 
---
---
> New design flights

- app/controllers/admin/dashboard_controller.rb
- app/models/card_charge.rb
- app/models/climate_report_invoice.rb
- app/models/invoice.rb
- app/views/admin/dashboard/index.html.erb
This would be easier to do with a refactoring to log sold co2e (and not just amount paid) for `CardCharges` in place. But this works until that is in place.
> Co2e per month in admin dashboard

- app/assets/main/components/README.md
- app/assets/main/components/modal.scss
- app/assets/main/controllers/modal_controller.js
- app/assets/main/index.scss
Example modal. Styles for overlay, modal window, close button, alignment of modal actions are implemented in this PR. Styling for modal content, in this case the heading and text, is up to implementation of each modal for flexibility.
> Add modal component

- app/controllers/users/subscriptions_controller.rb
- app/views/users/subscriptions/show.html.erb
- config/locales/views/subscriptions.en.yml
- config/locales/views/subscriptions.sv.yml
- spec/features/registrations_spec.rb
> Use new modal component for cancelling subscription

- app/controllers/users/subscriptions_controller.rb
- app/models/subscription_cancellation_feedback.rb
- app/views/users/subscriptions/show.html.erb
- config/locales/views/subscriptions.en.yml
- config/locales/views/subscriptions.sv.yml
- db/migrate/20200903125622_create_subscription_cancellation_feedbacks.rb
- db/schema.rb
Of course should be merged into master but doing it like this makes it really easy to see which commits are actually pushed in this branch.
> Offboarding

- app/controllers/users/subscriptions_controller.rb
- app/models/subscription_cancellation_feedback.rb
- app/views/users/subscriptions/show.html.erb
- config/locales/views/subscriptions.en.yml
- config/locales/views/subscriptions.sv.yml
- db/migrate/20200903125622_create_subscription_cancellation_feedbacks.rb
- db/schema.rb
😬 😬 😬 
Reverts goclimateneutral/goclimateneutral#375
> Revert "Revert "Offboarding""

- app/views/partners/bokanerja.html.erb
- app/views/partners/flygcity.html.erb
- app/views/partners/inshapetravel.html.erb
> New design on partner pages

- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/sessions/new.html.erb
Same design as `Log in` and `Forgot password` basically :blush:
> New design change password

- app/views/travel_calculator/show.html.erb
- config/locales/views/welcome.en.yml
- config/locales/views/welcome.sv.yml
- tailwind.config.js
https://goclimateneutral-stagin-pr-381.herokuapp.com/travel-calculator
> New design travel calculator

- app/views/users/receipts/index.html.erb
- app/views/users/subscriptions/show.html.erb
- config/locales/views/receipts.en.yml
- config/locales/views/receipts.sv.yml
- config/locales/views/subscriptions.en.yml
- config/locales/views/subscriptions.sv.yml
I also added a link to the receipts on the payment settings page.
https://goclimateneutral-stagin-pr-382.herokuapp.com/
> New design receipts

- app/assets/main/components/input.scss
- app/assets/main/components/tooltip.scss
- app/assets/main/index.scss
- app/views/business/climate_report_invoices/thank_you.html.erb
- app/views/business/climate_reports/new.html.erb
- app/views/business/climate_reports/show.html.erb
- app/views/business/contacts/create.html.erb
- config/locales/de.yml
- config/locales/en.yml
- config/locales/eo.yml
- config/locales/sv.yml
- spec/features/business_signup_spec.rb
Not perfect, but at least it's the new design.
I'm thinking on the report page perhaps we could have some sort of graphics to the right side of the actual report in the future.
https://goclimateneutral-stagin-pr-380.herokuapp.com/business/climate-reports/new
> New design business calculator

- app/assets/javascripts/users.js
- app/views/users/show.html.erb
Learning: don't use background colours on elements with `section-padding` class
> Small bugs on profile page

- app/controllers/dashboard_controller.rb
- app/models/user.rb
- app/views/dashboard/show.html.erb
- config/locales/en.yml
- config/locales/sv.yml
- spec/factories/user.rb
> Show lifestyle footprint on dashboard, divided by category

- .rubocop.yml
- spec/factories/user.rb
- spec/features/registrations_spec.rb
- spec/features/subscription_settings_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- spec/stripe_helpers.rb
- spec/support/feature_helper.rb
Ping @kallenilver @emmabckstrm, these changes will be good to know about.
> Add feature specs for editing subscription with and w/o 3D Secure card

- app/views/home/show.html.erb
- config/experiments.yml
- config/locales/views/welcome.de.yml
- config/locales/views/welcome.en.yml
- config/locales/views/welcome.eo.yml
- config/locales/views/welcome.sv.yml
The experiment has a clear winner, lets end it.
> End header experiment

- app/views/devise/registrations/new.html.erb
- config/experiments.yml
- config/locales/en.yml
- config/locales/sv.yml
- config/locales/views/registrations.de.yml
- config/locales/views/registrations.en.yml
- config/locales/views/registrations.eo.yml
- config/locales/views/registrations.sv.yml
> Categories on signup

- app/assets/main/controllers/membership_choice_controller.js
- app/assets/main/controllers/registration_form_controller.js
- app/controllers/dashboard_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/user.rb
- app/views/dashboard/show.html.erb
- app/views/devise/registrations/_sign_up_form.html.erb
- app/views/devise/registrations/_sign_up_form_without_subscription.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/layouts/application.html.erb
- config/locales/devise.views.en.yml
- config/locales/devise.views.sv.yml
- spec/features/registrations_spec.rb
Commits , 660084b, 6b2dbd1 and 3674412 are those changes that are actually in this PR. 
I will clean up commits when it comes time to merge, but for now I have wrestled with this long enough before making it reviewable. Will merge `sign-up-for-free-tempalte` into master before cleaning this one up to keep my sanity.
edit: see summary here https://github.com/goclimateneutral/goclimateneutral/pull/403#issuecomment-709287333
~~Also, there's a TODO regarding tracking that will need to be fixed before final reveal.~~
~~Note that this feature will be behind feature flag AND A/B test.~~
> Sign up without subscription 3

- app/models/card_charge.rb
- app/models/subscription_month.rb
- db/migrate/20201008093050_create_subscription_months.rb
- db/schema.rb
- spec/models/subscription_month_spec.rb
This is migrations to be merged before the rest of PR #404. See convo in that PR.
> Introduce subscription months model (migration)

- config/locales/views/shared.de.yml
- config/locales/views/shared.en.yml
- config/locales/views/shared.sv.yml
> Update copy for short about us footer text

- app/controllers/admin/referral_codes_controller.rb
- app/models/referral_code.rb
- app/models/subscription_month.rb
- app/models/user.rb
- app/views/admin/referral_codes/_form.html.erb
- app/views/admin/referral_codes/edit.html.erb
- app/views/admin/referral_codes/index.html.erb
- app/views/admin/referral_codes/new.html.erb
- app/views/admin/referral_codes/show.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- db/migrate/20201028072101_create_referral_codes.rb
- db/schema.rb
- spec/factories/lifestyle_footprint.rb
- spec/models/referral_code_spec.rb
Adding this in its own PR to avoid migration issues on the public site. I'll wait with merging this until the usage points are somewhat done in case some needs change along the way.
> Add referral codes

- config/routes.rb
Let's just rebase this on master after #408 has been merged so we can see them redirect to the correct place :).
> Hard-code upcoming partnership redirects

- db/migrate/20201105092740_add_first_subscription_created_at_to_users.rb
- db/schema.rb
This is a prerequisite to https://github.com/goclimateneutral/goclimateneutral/pull/423 and will be merged first.
> Add first_subscription_created_at column to Users

- app/controllers/referral_codes_controller.rb
- config/routes.rb
> Add vanity redirects for ReferralCodes with a destination_path

- db/migrate/20201112094713_add_country_and_yearly_footprint_to_gift_cards.rb
- db/schema.rb
> Migrations for country specific gift cards

- app/controllers/application_controller.rb
- app/controllers/gift_card_certificates_controller.rb
- app/controllers/gift_cards_controller.rb
- app/models/gift_card.rb
- app/models/lifestyle_footprint_average.rb
- app/pdfs/gift_card_certificate_pdf.rb
- app/views/gift_cards/index.html.erb
- app/views/gift_cards/new.html.erb
- app/views/home/show.html.erb
- app/views/pdfs/gift_card.html.erb
- config/locales/views/gift_cards.de.yml
- config/locales/views/gift_cards.en.yml
- config/locales/views/gift_cards.eo.yml
- config/locales/views/gift_cards.sv.yml
- db/migrate/20201112094713_add_country_to_gift_cards.rb
- lib/tasks/generate_gift_card_certifikates.rake
- spec/factories/gift_card.rb
- spec/mailers/previews/gift_card_mailer_preview.rb
- spec/models/gift_card_spec.rb
- spec/pdfs/gift_card_certificate_pdf_spec.rb
> Country specific gift cards

- db/migrate/20201125135617_add_home_area_to_lifestyle_footprints_and_lifestyle_calculators.rb
- db/schema.rb
> Clarify home area questions (migrations for #447)

- db/migrate/20210115143904_create_newsletter_subscribers.rb
- db/schema.rb
Just the migration commit. Full pr https://github.com/goclimate/goclimate/pull/458/
> Migrations for sign up for newsletter table

- app/assets/main/components/button.css
- app/assets/main/components/input.css
- app/assets/main/controllers/newsletter_subscription_controller.js
- app/controllers/newsletter_subscribers_controller.rb
- app/models/newsletter_subscriber.rb
- app/views/shared/_footer.html.erb
- config/locales/views/shared.en.yml
- config/locales/views/shared.sv.yml
- config/routes.rb
- spec/factories/newsletter_subscriber.rb
- spec/features/sessions_spec.rb
- spec/features/subscription_receipts_spec.rb
- spec/models/newsletter_subscriber_spec.rb
- spec/support/feature_helper.rb
I did some changes to make this work well and look good
- Added `sm` versions of our button and input CSS components
- New table (will be merged in separate PR)
- Small updates to design of footer to keep it a little more visually balanced
- Some changes in specs that could't distinguish the "email" field the were supposed to use when logging in vs the new I added (don't know why it had issues, the only name that was similar was the placeholder in the new input field 🤷‍♀️ )
> Sign up for newsletter

- app/assets/main/controllers/lifestyle_footprints/calculator_controller.js
- app/views/lifestyle_footprints/new.html.erb
I had some feeling and updated the UX for our calculator. I think viewing commit per commit shows the progress. We now have checkmarks and show the chosen option.
> UX update for calculator

- db/migrate/20210125121500_add_shopping_to_lifestyle_calculators_and_lifestyle_footprints.rb
- db/schema.rb
> Migrate DB fields for shopping question in calculator

- app/controllers/admin/lifestyle_calculator_previews_controller.rb
- app/controllers/admin/lifestyle_calculators_controller.rb
- app/controllers/lifestyle_footprints_controller.rb
- app/models/lifestyle_calculator.rb
- app/models/lifestyle_footprint.rb
- app/views/admin/lifestyle_calculators/new.html.erb
- app/views/admin/lifestyle_calculators/review.html.erb
- app/views/admin/lifestyle_calculators/show.html.erb
- app/views/lifestyle_footprints/new.html.erb
- config/locales/views/lifestyle_footprints.en.yml
- config/locales/views/lifestyle_footprints.sv.yml
- db/migrate/20210125121500_add_shopping_to_lifestyle_calculators_and_lifestyle_footprints.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/lifestyle_calculator.rb
- spec/factories/lifestyle_footprint.rb
- spec/features/registrations_spec.rb
- spec/models/lifestyle_calculator_spec.rb
- spec/models/lifestyle_footprint_spec.rb
Pretty much boils down to this screenshot, see discussion on Slack.
> Add shopping question to lifestyle calculator

- app/controllers/admin/flight_batch_controller.rb
- app/views/admin/flight_batch/create.html.erb
- app/views/admin/flight_batch/new.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
Most likely to be removed when we build a better tool for our customers to use. But hopefully useful until then.
> Temporary admin-tool to batch calculate emissions from flights

- app/controllers/admin/climate_reports_controller.rb
- app/controllers/admin/organizations_controller.rb
- app/models/climate_reports/report.rb
- app/models/organization.rb
- app/views/admin/climate_reports/_form.html.erb
- app/views/admin/climate_reports/edit.html.erb
- app/views/admin/climate_reports/index.html.erb
- app/views/admin/climate_reports/new.html.erb
- app/views/admin/climate_reports/show.html.erb
- app/views/admin/organizations/_form.html.erb
- app/views/admin/organizations/edit.html.erb
- app/views/admin/organizations/index.html.erb
- app/views/admin/organizations/new.html.erb
- app/views/admin/organizations/show.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- db/migrate/20210303092520_create_organizations.rb
- db/migrate/20210303092650_create_climate_reports_reports.rb
- db/schema.rb
- spec/models/organization_spec.rb
This PR changes the order of the migrations, meaning that before running this migration, production db needs to rollback two steps.
> Admin views for creating orginaztions and climate reports

- app/controllers/admin/business_calculators_controller.rb
- app/controllers/admin/climate_reports_controller.rb
- app/models/business_calculators/calculator.rb
- app/views/admin/business_calculators/index.html.erb
- config/routes.rb
- db/migrate/20210415110613_add_status_to_business_calculators.rb
- db/schema.rb
Only possible to 
- use published calculators
- edit draft calculators
> Give Business calculators status.

- app/controllers/about/cookies_controller.rb
- app/views/about/cookies/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
- config/locales/views/shared.en.yml
- config/locales/views/shared.sv.yml
- config/routes.rb
I added this to check all the compliance boxes I think we need
> Cookies policy added for compliance

- app/controllers/admin/business_calculators_controller.rb
- app/controllers/data_reporters_controller.rb
- app/controllers/reported_datas_controller.rb
- app/models/climate_reports/report_area.rb
- app/models/reported_data.rb
- app/views/admin/business_calculators/_form.html.erb
- app/views/data_reporters/show.html.erb
- app/views/reported_datas/new.html.erb
- app/views/reported_datas/thank_you.html.erb
- config/locales/views/data_reporters.en.yml
- config/locales/views/data_reporters.sv.yml
- config/locales/views/reported_datas.en.yml
- config/locales/views/reported_datas.sv.yml
- db/migrate/20210505142909_add_description_to_business_calculator_categories.rb
- db/schema.rb
Multiple changes to the user form for the business product.
Mainly:
- Translations
- First iteration of answered questions progress
- Show time period for report
- Shows description for calculator category
> User form changes

- app/views/reported_datas/_form.html.erb
This reverts commit 7cebd9a5b12ac3c6deb270a9a771ca438e5160a9.
> Revert "View handles a graceful transition of switching between using units to alternatives"

- app/controllers/price_increase_confirmation_controller.rb
- app/models/price_increase_confirmation.rb
- app/models/user.rb
- app/views/price_increase_confirmation/new.html.erb
- app/views/price_increase_confirmation/thank_you.html.erb
- config/routes.rb
- db/migrate/20210611090248_create_price_increase_confirmation.rb
- db/schema.rb
- spec/factories/card_charge.rb
- spec/models/user_spec.rb
> Price increase opt out page

- db/migrate/20210708080429_add_name_to_lifestyle_footprint.rb
- db/schema.rb
Migration for https://github.com/goclimate/goclimate/pull/529
> Migration for adding name to Lifestylefootprints

- app/controllers/lifestyle_footprints_controller.rb
- app/views/dashboard/show.html.erb
- app/views/lifestyle_footprints/index.html.erb
- app/views/lifestyle_footprints/show.html.erb
- app/views/shared/_chart_categories.html.erb
- app/views/shared/_header.html.erb
- config/locales/views/lifestyle_footprints.en.yml
- config/locales/views/lifestyle_footprints.sv.yml
- config/locales/views/shared.en.yml
- config/locales/views/shared.sv.yml
- config/routes.rb
- tailwind.config.js
> Lifestyle footprint improvements

- app/controllers/admin/lifestyle_footprints_controller.rb
- app/controllers/admin/users_controller.rb
- app/views/admin/lifestyle_footprints/index.html.erb
- app/views/admin/lifestyle_footprints/show.html.erb
- app/views/admin/users/index.html.erb
- app/views/admin/users/show.html.erb
- config/routes.rb
- report.20210817.150352.67299.0.001.json
Make it possible to view lifestyle footprints from user view in admin so that it is easier to handle customer support.
Waiting for https://github.com/goclimate/goclimate/pull/536
> Make it possible to view lifestyle footprints from user view in admin

- db/migrate/20210916123617_remove_foreign_key_from_newsletter_subscribers.rb
- db/migrate/20210916123738_add_newsletter_type_to_newsletter_subscribers.rb
- db/schema.rb
Migrations for https://github.com/goclimate/goclimate/pull/565
> Business newsletter subscriber migrations

- app/assets/admin/controllers/add_alternatives_controller.js
- app/assets/admin/controllers/data_collection_form_controller.js
- app/assets/admin/controllers/item_order_controller.js
- app/assets/admin/controllers/units_and_question_types_controller.js
- app/assets/shared/components/button.css
- app/assets/shared/components/lists.css
- app/controllers/admin/business_calculators_controller.rb
- app/views/admin/business_calculators/_add_field.html.erb
- app/views/admin/business_calculators/_field_layout.html.erb
- app/views/admin/business_calculators/_form.html.erb
- app/views/admin/business_calculators/index.html.erb
- app/views/admin/business_calculators/new.html.erb
- app/views/admin/business_calculators/show.html.erb
- app/views/admin/climate_reports/show.html.erb
- app/views/admin/organizations/show.html.erb
- app/views/admin/shared/_notice_banner.html.erb
- app/views/reported_datas/_field.html.erb
- app/views/reported_datas/_form.html.erb
> Data collection ux improvements
