goclimate/goclimate

- app/assets/stylesheets/base.scss
This is not code I am proud of, but a quick fix that will be discared in the future as we migrate away from custom css
> Chevron are correct size after removal of .site-wrapper class

- app/models/lifestyle_footprint.rb
- app/views/lifestyle_footprints/new.html.erb
- spec/models/lifestyle_footprint_spec.rb
Before this change, you could give yourself a "discount" on your
footprint by entering negative numbers :).
Setting min="0" on <input type="number"> seems to be enough in both
Safari/WebKit and Firefox to also stop the stepper from going below
zero. Entering a negative value will still result in not being able to
click Next to finish the calculator, but hopefully this case is
extremely rare.
> Disallow negative distances/flight hours in calculator

- app/controllers/lifestyle_footprints_controller.rb
- app/models/lifestyle_footprint.rb
- app/views/lifestyle_footprints/new.html.erb
- spec/factories/lifestyle_footprint.rb
- spec/models/lifestyle_footprint_spec.rb
We'd like to be able to prompt users when updated calculators for their
country are published.
> Persist country for LifestyleFootprint for future use

- app/controllers/application_controller.rb
- app/helpers/application_helper.rb
- app/models/experiments_assignment.rb
- app/views/layouts/application.html.erb
- app/views/welcome/index.html.erb
- config/experiments.yml
- spec/features/registrations_spec.rb
- spec/models/experiments_assignment_spec.rb
To run an experiment, just add it to `config/experiments.yml` with the desired frequency (for new sessions, resets after 30 days). Then just call `experiment_active?` with the symbolized name of the experiment to check if it is currently assigned.
We can link to experiments by using the `enable_experiments` and `disable_experiments` query params, like this: `https://www.goclimateneutral.org/?enable_experiments=new_calculator` and to disable: `https://www.goclimateneutral.org/?disable_experiments=new_calculator`. These get saved to the cookie like others so subsequent page views/visits keep that preference.
Experiments get reported to Google Analytics as a (sorted) comma separated string to the custom dimension called 'Experiments' (`dimension1`). If no experiment is active, it's reported …
> Add simple experiments infrastructure with YML config

- config/webpack/common.js
We've grown in entrypoints and module usage, leading to many chunks
being generated and most of them necessary to load initially for all
primary site visitors. This generates uneccessary requests and makes
debugging confusing when our sources are spread among many entrypoints.
This change changes chunks to only apply to the main entrypoints, and to
only ever create one chunk for modules. This lets the modules be cached
for a longer time, while keeping the number of requests down. API/admin
entrypoints are now fat, including all their modules, but those are
fewer both in dependencies and number of visitors.
> Split only one chunk for node_modules used by main JS entrypoint

- app/assets/main/components/button.scss
- app/assets/main/components/callout.scss
- app/assets/main/components/dropdown.scss
- app/assets/main/components/input.scss
- app/assets/main/components/lists.scss
- app/assets/main/index.scss
- app/controllers/application_controller.rb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/passwords/new_new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/sessions/new_new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_error_messages_old.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_header_old_tailwind.html.erb
- config/locales/en.yml
- config/locales/sv.yml
- tailwind.config.js
Looks like this:
---
Also sets new defaults for rounded corners and drop shadows. Two of each is all you get for now, one default for smaller things (like buttons & dropdown menus) and one large for... well larger things (like callout boxes). I don't see anything else right now so let's add more when we know what they're for?
> New design for login pages

- app/models/invoice.rb
It's important that we register all offset-invoices in our system to keep track of CO2e left total and left in every project. So far the check that everything is registered has been done manually now and then. By making project optional we can add all invoices to Invoice, even ones without a project, which makes it easy to track which invoices are not registered yet. This will also have the side effect that we can keep track of business income in our app.
> Make project optional for invoices

- app/controllers/sitemap_controller.rb
- app/views/sitemap/_common.xml.builder
- app/views/sitemap/content.xml.builder
- app/views/sitemap/index.xml.builder
- config/routes.rb
- public/robots.txt
I evaluated the SitemapGenerator gem that generats a sitemap and saves it to s3 (since heroku can't save files more then temporary). But since our generation of urls are not very load heavy yet and the SitemapGenerator version ended up a bit more complex than I felt comfortable with (s3 account, heroku scheduler, more gems, more magic etc) I ended up with this version. Simple, but maybe a bit wordier with less magic stuff helping out with the xml generation.
> Add really simple sitemap

- config/routes.rb
- spec/routing/redirect_routs_spec.rb
Since 'our_projects' is considered one word by search engines and 'our-projects' two words we want to replace _ with - in urls.
> Change underscore in urls to dash for seo reasons

- app/views/home/show_new.html.erb
- app/views/shared/_bottom_landscape.html.erb
The grass in the hero and prefooter illustrations were imporperly offset, however issue was only present in Chrome browsers.
> Fix illustration offset bug

- app/assets/main/components/lists.scss
- app/views/dashboard/show_new.html.erb
- app/views/shared/_footer.html.erb
- config/locales/en.yml
- config/locales/sv.yml
- spec/features/sessions_spec.rb
- Blue background to a) separate from public pages and b) green became too much green
- Fewer colour changes in the "You have been climate neutral for 1 month" text to keep it less all over the place/give it more harmony
- Possibility to add illustration to Share section
- The footer is used here, but with added possibility of skipping the prefooter, as the person is already logged in and don't need to sign up
> New design dashboard

- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/unprocessable_entity.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_prefooter.html.erb
- tailwind.config.js
Super quick and easy translation of new design onto error pages.
> New design on error pages

- app/views/business/show.html.erb
It's far from perfect but it's better than the old design :) 
The callout box around the logos is because some of the logos are screenshots against a white background, so I took this shortcut.
https://goclimateneutral-stagin-pr-378.herokuapp.com/business
> New design on For Business page

- .eslintrc.json
- app/assets/main/components/README.md
- app/assets/main/components/tabs.scss
- app/assets/main/controllers/tabs_controller.js
- app/assets/main/index.scss
- tailwind.config.js
In this version, there are only tabs from breakpoint `m-lg` and upward. Mobile view show the tab panels in a single column below each other
> Add tabs component

- app/views/application/_third_party_javascripts.html.erb
- app/views/layouts/application.html.erb
After discussions with @kallenilver we have decided to remove Google Tag Manager as it is not being used and not really relevant for our site. 
Regarding the tracking of local events or not - I have chosen to keep the scope on our current focus and added a card for handling local tracking later on https://trello.com/c/ZboMkrD4 - as it's not something that is being introduced now, rather an issue we have had since who knows.
@stefanlindbohm did you want some other sort of testing for this or is it fine to keep an eye on our tracking services in production?
> Remove Google tag manager tracking

- app/assets/main/controllers/referral_code_controller.js
- app/assets/main/controllers/registration_form_controller.js
- app/controllers/referral_codes_controller.rb
- app/controllers/users/registrations_controller.rb
- app/controllers/users/subscriptions_controller.rb
- app/models/subscription_manager.rb
- app/models/user.rb
- app/views/devise/registrations/_sign_up_form_without_subscription.html.erb
- app/views/devise/registrations/new_campaign.html.erb
- config/locales/views/registrations.en.yml
- config/locales/views/registrations.sv.yml
- config/routes.rb
- db/migrate/20201031191901_alter_referral_codes_index.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/referral_code.rb
- spec/features/registrations_spec.rb
- spec/fixtures/files/stripe/subscription.json
- spec/models/subscription_manager_spec.rb
- spec/models/user_spec.rb
Sign up page markup & JS is getting complicated, but this should work well for now.
> Add referral codes to sign up page

- app/controllers/about/transparency_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/home_controller.rb
- app/models/user.rb
- app/views/about/transparency/show.html.erb
- app/views/dashboard/show.html.erb
- app/views/home/show.html.erb
- config/locales/de.yml
- config/locales/en.yml
- config/locales/sv.yml
- spec/models/user_spec.rb
Since we now allow signing up for an account without starting a subscription and we have to goal of helping those users make an impact in other ways than offsetting too, we want to include those in the number of community members too.
> Show total users as member count

- app/views/users/subscriptions/show.html.erb
- config/locales/de.yml
- config/locales/en.yml
- config/locales/eo.yml
- config/locales/sv.yml
- spec/features/subscription_settings_spec.rb
Fixes a crash that one runs into when posting subscription settings in cases where no card is tied to the account and not having filled in new card details.
Looks like this when no card is tied to the account:
And like before when a card is tied to the account:
> Force adding a new card when absent in subscription settings

- app/views/shared/_chart_categories.html.erb
- config/locales/de.yml
- config/locales/en.yml
- config/locales/sv.yml
> Display shopping separately from public emissions in footprint charts

- app/assets/bundles/main.js
- app/assets/main/components/README.md
- app/assets/main/components/lists.scss
- app/assets/main/components/select.scss
- app/assets/main/controllers/modal_controller.js
- app/views/about/faq/show.html.erb
- app/views/about/show.html.erb
- app/views/dashboard/show.html.erb
- app/views/devise/registrations/_footer.html.erb
- app/views/devise/registrations/_sign_up_form.erb
- app/views/devise/registrations/new_campaign.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/flight_footprints/new.html.erb
- app/views/flight_offsets/new.html.erb
- app/views/gift_cards/new.html.erb
- app/views/home/show.html.erb
- app/views/lifestyle_footprints/new.html.erb
- app/views/projects/index.html.erb
- app/views/shared/_chart_categories.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_header.html.erb
- app/views/users/show.html.erb
- app/views/users/subscriptions/show.html.erb
- package.json
- yarn.lock
Icons we used for footprint charts are better visually balanced with this. And we have access to more icons should we need them.
Before:
After:
> Upgrade to Font Awesome 5

- .gitignore
- config/application.rb
- config/database.yml
Moving database name configuration from default to development to clarify that production database name is configured through environment variables. Production configuration is unaffected, that is.
We need to do this to stay up to date (if you have any data needed for development in your dev DB, first add it to `seeds.rb` so we all can get the benefit of that):
1. Stop the Rails server, Guard and anything else connected to the DB
2. Stop Postgres: `pg_ctl -D db/goclimateneutral stop`
3. Rename the data directory: `mv db/goclimateneutral db/goclimate`
4. Start Postgres: `pg_ctl -D db/goclimate start`
5. Reset the DB: `bin/rails db:reset`
> Rename last occurances of goclimateneutral to goclimate

- app/controllers/lifestyle_footprints_controller.rb
- app/views/lifestyle_footprints/new.html.erb
- spec/features/registrations_spec.rb
Cleans up from quick fix in 851756f.
A few learnings:
- Passing a single object to a path helper that doesn't take an ID
replaces the implicit use of params for that request (in this case
causing the disappearance of the region param in the path)
- With routes for the same resources defined twice, form_with seems
confused about which of them to use, even when each action is only
present in either of the two routes. Specifying both model and url
solves this.
> Cleanup fix for region being dropped in signup since e6f5ca1

- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
- config/locales/views/shared.en.yml
- config/locales/views/shared.sv.yml
- Added a very basic cookie consent banner
- Small design changes in footer so the privacy policy link is not blocked by the intercom bubble
Next step would be to have more information on what cookies we actually use and to deny them.
> Add very basic cookie consent banner

- app/models/user.rb
- app/views/devise/registrations/_sign_up_form.erb
- config/application.rb
- config/locales/activerecord.de.yml
- config/locales/activerecord.en.yml
- config/locales/activerecord.sv.yml
- spec/models/user_spec.rb
I have tested the regex as follows:
The reason for updating the formatting of the auto error messages from Activerecord is that it by default show the field that's causing the error (see image below). I removed the "Email" prefix
> Email validation when signing up

- app/views/users/subscriptions/show.html.erb
I think the current situation is a little bit confusing. This change aims to:
- Draw less attention to cancelling your subscription.
- Clarify that the danger is actually happening when clicking cancel in
the modal.
> Tweak cancellation buttons

- Gemfile
- Guardfile
- app/controllers/flight_footprints_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/greenhouse_gases.rb
- app/views/devise/registrations/_chart_world_comparison.html.erb
- app/views/devise/registrations/new_campaign.html.erb
- app/views/projects/index.html.erb
- app/views/users/subscriptions/show.html.erb
- config/locales/models.de.yml
- config/locales/models.en.yml
- config/locales/models.eo.yml
- config/locales/models.sv.yml
- spec/models/greenhouse_gases_spec.rb
Changes:
- Doesn't switch automatically between kgs and tonnes. Do that explicitly instead.
- Now uses delimiters and separators from current locale.
Specifically to adress the request to make admin dashboard more legible:
> Cleanup ghg formatting

- Gemfile
- Gemfile.lock
I lovveeee this gem.  💟 
Let's please add this?
Eg:
`irb(main):002:0>  FlightOffset.last`
`FlightOffset Load (0.4ms)  SELECT "flight_offsets".* FROM "flight_offsets" ORDER BY "flight_offsets"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<FlightOffset id: 11, created_at: "2021-09-09 14:13:53", updated_at: "2021-09-09 14:13:56", key: "dff8dfdef8158c356cdc4d5fa5e67103ade16749", co2e: 300 kg CO2e, email: "nandita__111@goclimate.com", stripe_charge_id: nil, price: 180, currency: #<struct Currency iso_code=:eur, rounding_precision=-1, small_amount_price_step=50, large_amount_price_step=100>, payment_intent_id: "pi_3JXo0jHwuhGySQCd0uttRGTV", paid_at: "2021-09-09 14:13:56", user_id: nil>`
**with gem**
> Adding gem awesome print where it pretty prints ruby objects
